
function getDados(){
    return{
        receitas: [{
            titulo : "Muffins de Ovos e Vegetais",  
            ingredientes : [
               "• ovos",
                "• espinafre picado",
                "• sal",
                "• pimenta",
                "• tomate picado",
                "•  cebola picada",
                "• queijo ralado (opcional)",
            ],
            modoDePreparo:"Pré-aqueça o forno a 180°C. Em uma tigela, bata os ovos e tempere com sal e pimenta. Adicione o espinafre, tomate, cebola e queijo (se estiver usando) e misture bem. Despeje a mistura em forminhas de muffin untadas com óleo ou forradas com forminhas de papel. Asse por cerca de 20-25 minutos, ou até que os muffins estejam firmes e dourados.",
            imgSrc: "./assets/image.png",
            reversed:false,
        },
        {
            titulo : "Pão de Queijo de Frigideira:",  
            ingredientes : [
               "• polvilho azedo",
                "• queijo parmesão ralado",
               "• ovo",
               "• leite",
                "• sal",
            ],
            modoDePreparo:"Em uma tigela, misture o polvilho azedo e o queijo parmesão ralado. Adicione o ovo, o leite e uma pitada de sal e misture até obter uma massa homogénea. Despeje a massa em urna frigideira antiaderente pré-aquecida e cozinhe em fago médio-baixo por cerca de 3-4 minutos de cada lado, ou até que o pão de queijo esteja dourado e firme.",
            imgSrc: "./assets/image2.png",
            reversed:true,
        },
        {
            titulo : "Frittata de Legumes Assadas",  
            ingredientes : [
               "• ovos",
               "• espinafre",
                "• tomate",
                "• cogumelos",
                "• cebola",
                "• sal",
                "• queijo ralado (opcional)",
                "• pimenta",
            ],
            modoDePreparo:"Pré-aqueça o forno a 180°C. Em uma frigideira que possa ir ao forno, refogue os vegetais de sua escolha até que estejam macios. Em uma tigela, bata os ovos e tempere com sal e pimenta. Despeje os ovos sobre os vegetais na frigideira e misture delicadamente. Cozinhe em fogo médio-baixo por alguns minutos até que as bordas comecem a firmar. Transfira a frigideira para o forno e asse por cerca de 10-15 minutos, ou até que a frittata esteja firme e dourada por cima.",
            imgSrc: "./assets/image3.png",
            reversed:false,
        },
        {
            titulo : "Bolo de Caneca Low Carb de Chocolate",  
            ingredientes : [
                "• farinha de amêndoa",
                "• cacau em pó sem açúcar",
                "• adoçante low carb",
                "• ovo",
                "• leite de amêndoa",
                "• óleo de coco (ou manteiga derretida)",
                "• essência de baunilha",
                "• fermento em pó",
            ],
            modoDePreparo:"Em uma caneca, misture todos os ingredientes secos Adicione o ovo, o leite de amêndoa, o óleo de coco (ou manteiga derretida) e a essência de baunilha à mistura seca e mexa bem até ficar homogêneo. Leve ao micro-ondas por cerca de 1-2 minutos, ou até que o bolo esteja cozido. Deixe esfriar por alguns minutos antes de servir.",
            imgSrc: "./assets/image4.png",
            reversed:true,
        },
        {
            titulo : "Tigela de Aveia de Chia com \n Leite de Amêndoa e Frutas",  
            ingredientes : [
               "• sementes de chia",
                "• leite de amêndoa",
                "• extrato de baunilha",
                "• adoçante (opcional)",
                "• frutas picadas (como morangos, mirtilos, framboesas.)",
                "• nozes picadas ",
            ],  
            modoDePreparo:"Em uma tigela, misture as sementes de chia, o leite de amêndoa, o extrato de baunilha e o adoçante (se estiver usando). Deixe descansar na geladeira por algumas horas ou durante a noite. Na hora de servir, cubra com frutas picadas e nazes",
            imgSrc: "./assets/image5.png",
            reversed:false,
        },
        {
            titulo : "Pudim de Chia com Leite de Coco e Manga",  
            ingredientes : [
               "• sementes de chia",
                "• leite de coco",
                "• manga picada",
                "• adoçante low carb(opcional)",
                "• coco ralado (opcional)",
            ],
            modoDePreparo:"Em uma tigela, misture as sementes de chia e a leite de coco. Adicione o adoçante, se desejar. Deixe descansar na geladeira por algumas horas ou durante a noite. Na hora de servir, cubra com pedaços de manga e coco rallado, se desejar.",
            imgSrc: "./assets/image6.png",
            reversed:true,
        },
        {
            titulo:"Ovos Benedict com Espinafre Salteado e Molho Hollandaise",
            ingredientes:[
                "• ovos",
                "• muffins ingleses low carb",
                "• bacon (opcional)",
                "• manteiga",
                "• suco de limão",
                "• sal",
                "• pimenta",
            ],
            modoDePreparo:"Prepare o molho hollandaise derretendo a manteiga em banho-maria e batendo com gemas de ovo e suco de limão até engrossar. Reserve. Prepare os ovos poché em água fervente com vinagre. Enquanto isso, refogue o espinafre em uma frigideira. Monte os ovos poché sobre os muffins ingleses, cubra com espinafre refogado e bacon, se desejar. e regue com molho hollandaise.",
            imgSrc:"./assets/image7.png",
            reversed:false,
        },
        {
            titulo:"Pão de Banana Low Carb com Nozes e Canela",
            ingredientes:[
                "• farinha de amêndoa",
                "• banana amassada",
                "• ovos",
                "• nozes picadas",
                "• canela",
                "• fermento em pó",
            ],
            modoDePreparo:"Pré-aqueça o forno a 180°C. Em uma tigela, misture a farinha de amêndoa, a banana amassada, os ovos, as nozes picadas, a canela e o fermento em på até formar uma massa homogènea. Despeje a massa em uma forma untada e asse por aproximadamente 25-30 minutos, ou até que esteja dourado e cozido por dentro.",
            imgSrc:"./assets/image8.png",
            reversed:true,
        },
        {
            titulo:"Biscoitos de Aveia e Cacau Sem Farinha",
            ingredientes:[
                "• aveia em flocos",
                "• cacau em pó sem açúcar",
                "• manteiga de amêndoa",
                "• mel ou adoçante low carb",
                "• ovos",
                "• fermento em pó",
            ],
            modoDePreparo:"Em uma tigela, misture a aveia em flocos, o cacau em pó, a manteiga de amêndoa, o mel ou adoçante, os ovos e o fermento em pó até formar uma massa homogénea. Faça pequenas porções da massa e coloque em uma assadeira forrada com papel manteiga. Asse em forno preaquecido a 180°C por cerca de 12-15 minutos, ou até que os biscoitos estejam firmes",
            imgSrc:"./assets/image9.png",
            reversed:false,
        },
        {
            titulo:"Bowl de Aveia de Sementes de Chia com Morangos e Nozes Picadas",
            ingredientes:[
                "• sementes de chia",
                "• leite de amêndoa",
                "• morangos picados",
                "• nozes picadas",
                "• canela",
                "• mel ou adoçante low carb",
            ],
            modoDePreparo:"Em uma tigela, misture as sementes de chia com o leite de amêndoa e deixe descansar na geladeira por algumas horas ou durante a noite. Na hora de servir, cubra com morangos picados, nozes picadas, canela e mel ou adoçante a gosto.",
            imgSrc:"./assets/image10.png",
            reversed:true,
        },
        {
            titulo:"Crepioca com Pasta de Amendoim e Banana",
            ingredientes:[
                "• tapioca",
                "• ovos",
                "• pasta de amendoim",
                "• banana",
                "• canela",
            ],
            modoDePreparo:"Misture a tapioca e os ovos até formar uma massa homogênea. Aqueça uma frigideira antiaderente e despeje a massa, espalhando para formar uma panqueca. Cozinhe dos dois lados até dourar. Em seguida, espalhe a pasta de amendoim sobre a crepioca, adicione fatias de banana e polvilhe com canela. Dobre ao meio e sirva.",
            imgSrc:"./assets/image11.png",
            reversed:false,
        },
        {
            titulo:"Ovos Mexidos com Queijo Cheddar e Bacon",
            ingredientes:[
                "• ovos",
                "• queijo cheddar ralado",
                "• bacon",
                "• sal",
                "• pimenta",
            ],
            modoDePreparo:"Em uma frigideira, frite o bacon até ficar crocante. Retire da frigideira e reserve. Em outra tigela, bata os ovos e tempere com sa e pimenta. Despeje os ovos na frigideira e mexa delicadamente até que comecem a cozinhar. Adicione o queijo cheddar ralado e continue mexendo até que os ovos estejam cozidos. Sirva com o bacon por cima.",
            imgSrc:"./assets/image12.png",
            reversed:true,
        },
        {
            titulo:"Pão de Alho Low Carb com Ervas Frescas",
            ingredientes:[
                "• farinha de amêndoa",
                "• fermento em pó",
                "• alho picado",
                "• ervas frescas picadas \n (como salsinha, cebolinha, manjericão)",
                "• ovos",
                "• manteiga derretida",
                "• sal",
            ],
            modoDePreparo:"Pré-aqueça o forno a 180°C. Em uma tigela, misture a farinha de amêndoa, o fermento em pó, o alho picado e as ervas frescas picadas. Adicione os ovos e a manteiga derretida à mistura e misture bem. Despeje a massa em uma forma untada e leve ao forno por cerca de 25-30 minutos, ou até que esteja dourado e cozido por dentro.",
            imgSrc:"./assets/image13.png",
            reversed:false,
        },
        {
            titulo:"Pão de queijo de Batata Doce na Frigideira",
            ingredientes:[
                "• polvilho doce",
                "• sal",
                "• queijo minas padrão ralado",
                "• ovo",
                "• batata doce cozida e amassada",
            ],
            modoDePreparo:"Em uma tigela, misture a batata doce amassada, o polvilho doce, o queijo minas padrão ralado, o ovo e o sal até formar uma massa homogênea. Aqueça uma frigideira antiaderente untada com um pouco de óleo em fogo médio. Com uma colher, coloque porções da massa na frigideira e espalhe levemente para formar os pães de queijo. Deixe dourar de um lado e vire para dourar do outro lado. Sirva quente.",
            imgSrc:"./assets/image14.png",
            reversed:true,
        },
        {
            titulo:"Smoothie de Coco e Morango",
            ingredientes:[
                "• leite de coco",
                "• morangos congelados",
                "• iogurte grego natural",
                "• coco ralado sem açucar",
                "• gelo",
                "• adoçante low carb (opcional)",
            ],
            modoDePreparo: "Em um liquidificador, adicione o leite de coco, os morangos congelados, o iogurte grego, o coco ralado e o gelo. Adicione adoçante a gosto, se desejar. Bata até obter uma mistura cremosa e homogênea. Sirva imediatamente.",
            imgSrc:"./assets/image15.png",
            reversed:false,
        },
        {
            titulo:"Smoothie de Cacau e Banana",
            ingredientes:[
                "• banana congelada",
                "• leite de amêndoa",
                "• cacau em pó sem açúcar",
                "• manteiga de amêndoa",
                "• gelo",
                "• adoçante low carb (opcional)",
            ],
            modoDePreparo:"Em um liquidificador, combine a banana congelada, o leite de amêndoa, o cacau em pó, a manteiga de amêndoa e o gelo. Adicione adoçante a gosto, se desejar. Bata até obter uma mistura cremosa e homogénea. Sirva imediatamente.",
            imgSrc:"./assets/image16.png",
            reversed:true,
        },
        {
            titulo:"Barrinhas de Aveia e Frutas Secas",
            ingredientes:[
                "• aveia em flocos",
                "• tâmaras picadas",
                "• amêndoas picadas",
                "• castanhas-do-pará picadas",
                "• sementes de abóbora",
                "• mel ou maple syrup",
                "• manteiga de amêndoa",
            ],
            modoDePreparo:"Misture todos as ingredientes em uma tigela até que estejam bem incorporados. Espalhe a mistura em uma forma forrada com papel manteiga e pressione firmemente para compactar. Leve à geladeira por algumas horas até firmar. Corte em barrinhas e sirva.",
            imgSrc:"./assets/image17.png",
            reversed:false,
        },
        ]
    }
}